version: 2
updates:
- package-ecosystem: gomod
  directory: "/ayako"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  reviewers:
  - deissh
  assignees:
  - deissh
  labels:
  - dependencies
  - area/ayako
