version: '3.5'

services:
  db:
    image: postgres:11
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-osu-server}
    volumes:
      - /var/lib/postgresql/osu-lazer:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]

  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - /var/lib/redis/osu-lazer:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]

  backend:
    image: deissh/osu-lazer:${BACKEND_TAG:-latest}
    restart: unless-stopped
    build:
      context: .
    depends_on:
      - db
      - redis
    environment:
      DEBUG: false
      SERVER__DATABASE__DRIVER: postgres
      SERVER__DATABASE__DSN: postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db/${DB_NAME:-osu-server}
      SERVER__REDIS__HOST: redis:6379
      SERVER__HOST: 0.0.0.0
      SERVER__PORT: 2100
      SERVER__JWT_SECRET: ${DB_USER:-notset}
    ports:
      - 2100:2100
