debug: ${DEBUG|true}

# External services
services:
  avatars: 'https://a.localhost'
  cheesegull: 'https://storage.localhost'


# API server configuration
server:
  host: ${SERVER__HOST|127.0.0.1}
  port: ${SERVER__PORT|2100}

  sentry:
    enable: ${SERVER__SENTRY__ENABLE|false}
    dsn: ${SERVER__SENTRY__DSN}

  datadog:
    enable: ${SERVER__DATADOG__ENABLE|true}
    prefix: lazer.
    statsd_host: ${SERVER__DATADOG__STATSD_HOST|127.0.0.1:8126}

  jwt:
    secret: ${SERVER__JWT_SECRET}
    hours_before_revoke: 24

  database:
    driver: ${SERVER__DATABASE__DRIVER|postgres}
    dsn: ${SERVER__DATABASE__DSN|postgres://postgres:postgres@/osuserver?sslmode=disable}

  redis:
    host: ${SERVER__REDIS__HOST|127.0.0.1:6379}
    password: ${SERVER__REDIS__PASSWORD|}
    db: ${SERVER__REDIS__DB}

  mailgun:
    domain: ''
    private_key: ''
    public_key: ''
    from: ''
